# Generated by Django 6.0.3 on 2026-03-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_engagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
    ]
