# Generated by Django 6.0.3 on 2026-03-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_engagement', '0003_message_is_deleted_message_is_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='messagereport',
            name='reason',
            field=models.TextField(max_length=500),
        ),
    ]
