# Generated by Django 6.0.3 on 2026-03-29 11:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_engagement', '0004_alter_message_content_alter_messagereport_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='badges/')),
                ('rarity', models.CharField(choices=[('common', 'Commun'), ('uncommon', 'Peu commun'), ('rare', 'Rare'), ('epic', 'Épique'), ('legendary', 'Légendaire')], default='common', max_length=20)),
                ('points', models.IntegerField(default=10)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.IntegerField(unique=True)),
                ('points', models.IntegerField()),
                ('bonus_type', models.CharField(blank=True, choices=[('points', 'Points bonus'), ('multiplier', 'Multiplicateur temporaire'), ('badge', 'Badge'), ('frame', 'Cadre de profil'), ('title', 'Titre'), ('shield', 'Bouclier de streak')], max_length=20, null=True)),
                ('bonus_value', models.CharField(blank=True, max_length=100, null=True)),
                ('is_milestone', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('points_required', models.PositiveBigIntegerField()),
                ('color', models.CharField(default='#6c63ff', max_length=7)),
                ('perks', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ProfileFrame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='frames/')),
                ('rarity', models.CharField(choices=[('common', 'Commun'), ('rare', 'Rare'), ('epic', 'Épique'), ('legendary', 'Légendaire')], default='common', max_length=20)),
                ('css_class', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6c63ff', max_length=7)),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginRewardClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('streak_day', models.IntegerField()),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_engagement.dailyreward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-claimed_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginStreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_login_date', models.DateField(blank=True, null=True)),
                ('total_login_days', models.IntegerField(default=0)),
                ('shields', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserXP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_points', models.PositiveBigIntegerField(default=0)),
                ('current_points', models.PositiveBigIntegerField(default=0)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('multiplier_expires', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='community_engagement.level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('balance_after', models.PositiveBigIntegerField()),
                ('transaction_type', models.CharField(choices=[('earn', 'Gagné'), ('spend', 'Dépensé'), ('bonus', 'Bonus'), ('penalty', 'Pénalité')], max_length=20)),
                ('source', models.CharField(choices=[('daily_login', 'Connexion quotidienne'), ('streak_bonus', 'Bonus de streak'), ('achievement', 'Achievement'), ('forum', 'Forum'), ('manual', 'Manuel (admin)'), ('messaging', 'Meassage et convesation'), ('friend', 'Friends')], max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('multiplier_applied', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reward_type', models.CharField(choices=[('badge', 'Badge'), ('frame', 'Cadre'), ('title', 'Titre')], max_length=10)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('is_equipped', models.BooleanField(default=False)),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community_engagement.badge')),
                ('frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community_engagement.profileframe')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community_engagement.title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('badge__isnull', False), ('frame__isnull', False), ('title__isnull', False), _connector='OR'), name='userreward_has_at_least_one_reward'), models.UniqueConstraint(condition=models.Q(('badge__isnull', False)), fields=('user', 'badge'), name='unique_user_badge'), models.UniqueConstraint(condition=models.Q(('frame__isnull', False)), fields=('user', 'frame'), name='unique_user_frame'), models.UniqueConstraint(condition=models.Q(('title__isnull', False)), fields=('user', 'title'), name='unique_user_title'), models.UniqueConstraint(condition=models.Q(('is_equipped', True)), fields=('user', 'reward_type'), name='unique_equipped_per_type')],
            },
        ),
    ]
