# Generated by Django 6.0.3 on 2026-03-29 21:30

import random
import string
import django.core.validators


def _generate_code():
    """Inlined from the deleted Community.models.referrals module."""
    return ''.join(random.choices(string.ascii_uppercase + string.digits, k=16))
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_engagement', '0007_blogcategory_blogpost_blogcomment_event_showcaseitem_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('dau_count', models.IntegerField(default=0, help_text='Daily active users')),
                ('mau_count', models.IntegerField(default=0, help_text='Monthly active users')),
                ('new_users', models.IntegerField(default=0)),
                ('retention_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🎯', max_length=10)),
                ('challenge_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('seasonal', 'Seasonal')], default='daily', max_length=10)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('extreme', 'Extreme')], default='medium', max_length=10)),
                ('objectives', models.JSONField(default=list, help_text='List of objective dicts: [{key, label, target}]')),
                ('points_reward', models.IntegerField(default=100)),
                ('bonus_type', models.CharField(blank=True, help_text='badge/frame/title', max_length=20)),
                ('bonus_id', models.CharField(blank=True, help_text='UUID of the reward item', max_length=36)),
                ('participant_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('auto_refresh', models.BooleanField(default=True)),
                ('refresh_interval_days', models.PositiveIntegerField(default=1)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('campaign_type', models.CharField(choices=[('welcome', 'Welcome'), ('re_engagement', 'Re-engagement'), ('milestone', 'Milestone')], max_length=15)),
                ('trigger_days_inactive', models.IntegerField(blank=True, help_text='Days of inactivity to trigger (re-engagement only)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['campaign_type'],
            },
        ),
        migrations.CreateModel(
            name='EngagementFunnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('stage', models.IntegerField()),
                ('user_count', models.IntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date', 'stage'],
            },
        ),
        migrations.CreateModel(
            name='ProgressionPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('path_type', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('contributor', 'Contributor')], max_length=15, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🛤', max_length=10)),
                ('total_stages', models.IntegerField(default=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['path_type'],
            },
        ),
        migrations.CreateModel(
            name='ReactionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('emoji', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('standard', 'Standard'), ('css_specific', 'CSS Specific'), ('premium', 'Premium')], default='standard', max_length=15)),
                ('min_level_required', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReferralReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('basic', 'Basic (1–4 referrals)'), ('silver', 'Silver (5–9 referrals)'), ('gold', 'Gold (10–19 referrals)'), ('platinum', 'Platinum (20+ referrals)')], max_length=10, unique=True)),
                ('min_referrals', models.IntegerField()),
                ('max_referrals', models.IntegerField(blank=True, null=True)),
                ('points_per_referral', models.IntegerField(default=50)),
                ('bonus_type', models.CharField(blank=True, help_text='badge/frame/title', max_length=20)),
                ('bonus_value', models.CharField(blank=True, help_text='UUID of reward item', max_length=36)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['min_referrals'],
            },
        ),
        migrations.CreateModel(
            name='StreakBonus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('milestone_days', models.IntegerField(help_text='7, 30, 90, 365 etc.', unique=True)),
                ('points_awarded', models.IntegerField()),
                ('bonus_type', models.CharField(blank=True, choices=[('shield', 'Streak Shield'), ('frame', 'Profile Frame'), ('permanent_bonus', 'Permanent XP Bonus'), ('title', 'Title'), ('ultimate', 'Ultimate Reward')], max_length=20, null=True)),
                ('bonus_value', models.CharField(blank=True, help_text='UUID of reward item or percent string', max_length=100)),
                ('permanent_multiplier_bonus', models.DecimalField(decimal_places=2, default=0.0, help_text='e.g. 0.05 = +5%', max_digits=4)),
                ('description', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['milestone_days'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='group_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='conversation',
            name='group_participants',
            field=models.ManyToManyField(blank=True, related_name='group_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_archived_by',
            field=models.ManyToManyField(blank=True, related_name='archived_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='file_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('system', 'System')], default='text', max_length=10),
        ),
        migrations.CreateModel(
            name='CssBattle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('theme', models.CharField(max_length=100)),
                ('rules', models.TextField()),
                ('prize_description', models.TextField()),
                ('submission_start', models.DateTimeField()),
                ('submission_end', models.DateTimeField()),
                ('voting_start', models.DateTimeField()),
                ('voting_end', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submission_start'],
            },
        ),
        migrations.CreateModel(
            name='BattleSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('demo_html', models.TextField()),
                ('demo_css', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='battles/thumbnails/')),
                ('description', models.TextField(blank=True)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('vote_count', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_disqualified', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_submissions', to=settings.AUTH_USER_MODEL)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='community_engagement.cssbattle')),
            ],
            options={
                'ordering': ['-average_score'],
                'unique_together': {('battle', 'author')},
            },
        ),
        migrations.CreateModel(
            name='CssComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('css_item_id', models.IntegerField(db_index=True, help_text='PK of the CSS item from Shopping module')),
                ('content', models.TextField(max_length=1000)),
                ('is_question', models.BooleanField(default=False)),
                ('seller_answer', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='css_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_replies', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community_engagement.csscomment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('html_body', models.TextField()),
                ('text_body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='community_engagement.emailcampaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailSend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('is_bounced', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='community_engagement.emailcampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_sends', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='community_engagement.emailtemplate')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='EngagementScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_score', models.IntegerField(default=0)),
                ('social_score', models.IntegerField(default=0)),
                ('purchase_score', models.IntegerField(default=0)),
                ('content_score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical (churning)')], default='low', max_length=10)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_score', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_score'],
            },
        ),
        migrations.CreateModel(
            name='InactivityTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('days_inactive', models.IntegerField(choices=[(3, '3 days'), (7, '7 days'), (14, '14 days'), (30, '30 days'), (60, '60 days')])),
                ('action_type', models.CharField(choices=[('email', 'Send Email'), ('push', 'Send Push Notification'), ('notification', 'In-app Notification')], max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inactivity_triggers', to='community_engagement.emailcampaign')),
            ],
            options={
                'ordering': ['days_inactive'],
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(max_length=36)),
                ('is_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('mentioned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_mentions', to=settings.AUTH_USER_MODEL)),
                ('mentioned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_mentions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentionPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_mentions', models.CharField(choices=[('all', 'Everyone'), ('friends', 'Friends only'), ('nobody', 'Nobody')], default='all', max_length=10)),
                ('notify_on_mention', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mention_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('milestone_type', models.CharField(choices=[('first_sale', 'First Sale'), ('100th_purchase', '100th Purchase'), ('anniversary', 'Anniversary'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('points_reward', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='community_engagement.badge')),
            ],
            options={
                'ordering': ['milestone_type'],
            },
        ),
        migrations.CreateModel(
            name='MilestoneReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='community_engagement.milestone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-claimed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipped_badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='community_engagement.badge')),
                ('equipped_frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='community_engagement.profileframe')),
                ('equipped_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='community_engagement.title')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_customization', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PathMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('requirement_type', models.CharField(choices=[('purchases', 'CSS Purchases'), ('sales', 'CSS Sales'), ('posts', 'Forum Posts'), ('contributions', 'Content Contributions')], max_length=15)),
                ('requirement_value', models.IntegerField()),
                ('points_reward', models.IntegerField(default=0)),
                ('is_final', models.BooleanField(default=False)),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='community_engagement.badge')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='community_engagement.progressionpath')),
            ],
            options={
                'ordering': ['stage'],
            },
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=300)),
                ('action_url', models.CharField(blank=True, max_length=300)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh_key', models.CharField(max_length=200)),
                ('auth_key', models.CharField(max_length=100)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='📜', max_length=10)),
                ('points_reward', models.IntegerField(default=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unlock_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks', to='community_engagement.quest')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuestChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_engagement.challenge')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_challenges', to='community_engagement.quest')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='quest',
            name='challenges',
            field=models.ManyToManyField(related_name='quests', through='community_engagement.QuestChallenge', to='community_engagement.challenge'),
        ),
        migrations.CreateModel(
            name='QuestProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('active', 'Active'), ('completed', 'Completed')], default='active', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_challenges', models.ManyToManyField(blank=True, related_name='completions', to='community_engagement.challenge')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='community_engagement.quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReactionSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(max_length=36)),
                ('count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='community_engagement.reactiontype')),
            ],
            options={
                'ordering': ['-count'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
                ('reaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='community_engagement.reactiontype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReengagementAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_taken', models.DateTimeField(auto_now_add=True)),
                ('was_effective', models.BooleanField(blank=True, help_text='True if user returned within 7 days', null=True)),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='community_engagement.inactivitytrigger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reengagement_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-action_taken'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=_generate_code, max_length=16, unique=True)),
                ('custom_code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('use_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('converted', 'Converted'), ('rewarded', 'Rewarded')], default='pending', max_length=10)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('rewarded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_received', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_given', to=settings.AUTH_USER_MODEL)),
                ('code_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='community_engagement.referralcode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoreComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component_type', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('engagement_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='community_engagement.engagementscore')),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPathProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_stage', models.IntegerField(default=1)),
                ('completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='community_engagement.progressionpath')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='community_engagement.battlesubmission')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-voted_at'],
                'unique_together': {('submission', 'voter')},
            },
        ),
        migrations.AddIndex(
            model_name='csscomment',
            index=models.Index(fields=['css_item_id', 'status'], name='community_e_css_ite_75db5d_idx'),
        ),
        migrations.AddIndex(
            model_name='mention',
            index=models.Index(fields=['mentioned_user', 'is_notified'], name='community_e_mention_9640d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='milestonereward',
            unique_together={('user', 'milestone')},
        ),
        migrations.AlterUniqueTogether(
            name='pathmilestone',
            unique_together={('path', 'stage')},
        ),
        migrations.AlterUniqueTogether(
            name='questchallenge',
            unique_together={('quest', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='questprogress',
            unique_together={('user', 'quest')},
        ),
        migrations.AlterUniqueTogether(
            name='reactionsummary',
            unique_together={('content_type', 'object_id', 'reaction_type')},
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['content_type', 'object_id'], name='community_e_content_10a8e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('user', 'content_type', 'object_id', 'reaction_type')},
        ),
        migrations.AlterUniqueTogether(
            name='userblock',
            unique_together={('blocker', 'blocked')},
        ),
        migrations.AlterUniqueTogether(
            name='userpathprogress',
            unique_together={('user', 'path')},
        ),
    ]
