# Generated by Django 6.0.3 on 2026-04-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_engagement', '0008_activitymetric_challenge_emailcampaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xptransaction',
            name='source',
            field=models.CharField(choices=[('daily_login', 'Connexion quotidienne'), ('streak_bonus', 'Bonus de streak'), ('achievement', 'Achievement'), ('forum', 'Forum'), ('manual', 'Manuel (admin)'), ('messaging', 'Message et conversation'), ('friend', 'Friends'), ('leaderboard', 'Leaderboard'), ('reaction', 'Reaction'), ('referral', 'Referral'), ('challenge', 'Challenge')], max_length=50),
        ),
    ]
