# Generated by Django 6.0.1 on 2026-04-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_engagement', '0009_alter_xptransaction_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='advertisements',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='blog',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='forum',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('friend_request', "Demande d'ami"), ('friend_accept', 'Demande acceptée'), ('new_message', 'Nouveau message'), ('level_up', 'Niveau supérieur'), ('achievement', 'Achievement débloqué'), ('daily_reward', 'Récompense journalière'), ('new_follower', 'Nouveau suiveur'), ('streak_broken', 'Streak perdu'), ('streak_shield', 'Shield utilisé'), ('system', 'Système'), ('new_blog_post', 'Nouveau article'), ('blog_comment', 'Commentaire blog'), ('forum_reply', 'Réponse forum'), ('forum_mention', 'Mention forum'), ('order_update', 'Mise à jour commande'), ('ad_status', 'Statut publicité'), ('new_review', 'Nouvel avis'), ('mission_assigned', 'Mission assignée')], max_length=30),
        ),
    ]
