# Generated by Django 6.0.4 on 2026-04-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_engagement', '0012_merge_0011_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpreferences',
            name='show_achievements',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feedpreferences',
            name='show_level_ups',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feedpreferences',
            name='show_streaks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='achievements',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='level_ups',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='activityfeeditem',
            name='action_type',
            field=models.CharField(choices=[('level_up', 'Level Up'), ('achievement_unlocked', 'Achievement Unlocked'), ('friend_added', 'Friend Added'), ('follower_gained', 'New Follower'), ('streak_milestone', 'Streak Milestone'), ('daily_reward', 'Daily Reward')], max_length=30),
        ),
        migrations.AlterField(
            model_name='activityfeeditem',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('followers', 'Followers'), ('private', 'Private')], default='public', max_length=12),
        ),
        migrations.AlterField(
            model_name='feedpreferences',
            name='default_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('followers', 'Followers'), ('private', 'Private')], default='public', max_length=12),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('friend_accept', 'Friend Request Accepted'), ('new_message', 'New Message'), ('level_up', 'Level Up'), ('achievement', 'Achievement Unlocked'), ('daily_reward', 'Daily Reward'), ('new_follower', 'New Follower'), ('streak_broken', 'Streak Lost'), ('streak_shield', 'Shield Used'), ('system', 'System'), ('new_blog_post', 'New Blog Post'), ('blog_comment', 'Blog Comment'), ('forum_reply', 'Forum Reply'), ('forum_mention', 'Forum Mention'), ('order_update', 'Order Update'), ('ad_status', 'Ad Status'), ('new_review', 'New Review'), ('mission_assigned', 'Mission Assigned'), ('review_submitted', 'Content submitted for review')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10),
        ),
    ]
