# Generated by Django 6.0.4 on 2026-04-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_engagement', '0014_remove_ctf_hackathon_event_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedpreferences',
            name='show_achievements',
        ),
        migrations.RemoveField(
            model_name='feedpreferences',
            name='show_level_ups',
        ),
        migrations.RemoveField(
            model_name='feedpreferences',
            name='show_streaks',
        ),
        migrations.AddField(
            model_name='feedpreferences',
            name='show_blog_posts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feedpreferences',
            name='show_css',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feedpreferences',
            name='show_events',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feedpreferences',
            name='show_forum_posts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feedpreferences',
            name='show_reviews',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feedpreferences',
            name='show_showcases',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feedpreferences',
            name='show_tutorials',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='activityfeeditem',
            name='action_type',
            field=models.CharField(choices=[('friend_added', 'Friend Added'), ('follower_gained', 'New Follower'), ('blog_post_created', 'Article publié'), ('forum_topic_created', 'Sujet forum créé'), ('forum_post_created', 'Message forum posté'), ('showcase_added', 'Showcase ajouté'), ('tutorial_published', 'Tutoriel publié'), ('css_published', 'CSS publié'), ('review_posted', 'Avis posté'), ('event_joined', 'Événement rejoint')], max_length=30),
        ),
    ]
