# Generated by Django 6.0.4 on 2026-04-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_engagement', '0017_remove_games_showcase_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcaseitem',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
