# Generated by Django 6.0.4

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_engagement', '0018_alter_showcaseitem_is_approved_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BattleVote',
        ),
        migrations.DeleteModel(
            name='BattleSubmission',
        ),
        migrations.DeleteModel(
            name='CssBattle',
        ),
    ]
