# Generated by Django 5.2.1 on 2025-06-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cart',
            field=models.TextField(null=True),
        ),
    ]
