# Generated by Django 5.2.1 on 2025-06-05 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_userprofile_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bid',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
