# Generated by Django 5.2.7 on 2025-10-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_userprofile_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='biography',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='picture_path',
            field=models.CharField(blank=True, default='default.png', max_length=255),
        ),
    ]
