# Generated by Django 6.0.3 on 2026-03-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_profiletheme_purchasedfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_claimed_bonus',
            field=models.BooleanField(default=False),
        ),
    ]
