# Generated by Django 6.0.1 on 2026-01-16 19:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('template_type', models.CharField(choices=[('warning_notice', 'Warning - Notice'), ('warning_formal', 'Warning - Formal'), ('warning_final', 'Warning - Final'), ('mute_notification', 'Mute Notification'), ('report_dismissed', 'Report Dismissed'), ('report_actioned', 'Report Action Taken'), ('welcome', 'Welcome Message'), ('rule_reminder', 'Rule Reminder'), ('other', 'Other')], default='other', max_length=20)),
                ('subject', models.CharField(blank=True, help_text='Subject line (for notifications)', max_length=200)),
                ('content', models.TextField(help_text='Template content. Use {username}, {reason}, {date}, {moderator} as placeholders.', max_length=10000)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment or Bullying'), ('hate_speech', 'Hate Speech'), ('inappropriate', 'Inappropriate Content'), ('misinformation', 'Misinformation'), ('copyright', 'Copyright Violation'), ('personal_info', 'Personal Information Exposure'), ('off_topic', 'Off-topic'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the issue', max_length=2000, validators=[django.core.validators.MinLengthValidator(10)])),
                ('content_snapshot', models.TextField(blank=True, help_text='Snapshot of the reported content at time of report')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('action_taken', 'Action Taken'), ('dismissed', 'Dismissed'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='Priority level (1=low, 5=critical)')),
                ('resolution_notes', models.TextField(blank=True, help_text='Moderator notes on resolution', max_length=2000)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('action_warning_issued', models.BooleanField(default=False)),
                ('action_content_hidden', models.BooleanField(default=False)),
                ('action_content_deleted', models.BooleanField(default=False)),
                ('action_user_muted', models.BooleanField(default=False)),
                ('reporter_notified', models.BooleanField(default=False)),
                ('reporter_feedback', models.CharField(blank=True, max_length=500)),
                ('report_valid', models.BooleanField(help_text='Whether the report was valid', null=True)),
                ('reporter_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('reported_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='Forum.post')),
                ('reported_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='Forum.topic')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_reports_against', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_reports_filed', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeletedContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_id', models.UUIDField(help_text='Original content UUID')),
                ('content_type', models.CharField(choices=[('post', 'Post'), ('topic', 'Topic')], max_length=10)),
                ('original_author_username', models.CharField(blank=True, max_length=150)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(help_text='Full content at time of deletion')),
                ('content_html', models.TextField(blank=True, help_text='Rendered HTML at time of deletion')),
                ('category_name', models.CharField(blank=True, max_length=100)),
                ('topic_id', models.UUIDField(blank=True, null=True)),
                ('topic_title', models.CharField(blank=True, max_length=200)),
                ('deleted_by_username', models.CharField(blank=True, max_length=150)),
                ('deletion_reason', models.CharField(choices=[('user_request', 'User Request'), ('spam', 'Spam'), ('harassment', 'Harassment'), ('inappropriate', 'Inappropriate Content'), ('violation', 'Rule Violation'), ('duplicate', 'Duplicate Content'), ('moderation', 'Moderation Decision'), ('other', 'Other')], default='other', max_length=20)),
                ('deletion_notes', models.TextField(blank=True, help_text='Additional notes about the deletion', max_length=1000)),
                ('is_recoverable', models.BooleanField(default=True)),
                ('recovered', models.BooleanField(default=False)),
                ('recovered_at', models.DateTimeField(blank=True, null=True)),
                ('original_created_at', models.DateTimeField()),
                ('original_updated_at', models.DateTimeField()),
                ('original_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_content_deletions', to=settings.AUTH_USER_MODEL)),
                ('original_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_forum_content', to=settings.AUTH_USER_MODEL)),
                ('recovered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_content_recoveries', to=settings.AUTH_USER_MODEL)),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_content', to='Forum.report')),
            ],
            options={
                'verbose_name_plural': 'Deleted Content',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserWarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('notice', 'Notice'), ('warning', 'Warning'), ('final_warning', 'Final Warning')], default='warning', max_length=20)),
                ('reason', models.TextField(help_text='Detailed reason for the warning', max_length=1000, validators=[django.core.validators.MinLengthValidator(10)])),
                ('rule_violated', models.CharField(blank=True, help_text='Specific rule or guideline violated', max_length=200)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('points', models.PositiveIntegerField(default=1, help_text='Warning severity points')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_warnings', to=settings.AUTH_USER_MODEL)),
                ('related_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warnings', to='Forum.post')),
                ('related_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warnings', to='Forum.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_warnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_type', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('inappropriate', 'Inappropriate Content'), ('off_topic', 'Persistent Off-topic Posting'), ('violation', 'Rule Violation'), ('cooldown', 'Cooling Off Period'), ('other', 'Other')], default='other', max_length=20)),
                ('reason', models.TextField(help_text='Detailed reason for the mute', max_length=1000, validators=[django.core.validators.MinLengthValidator(10)])),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(help_text='When the mute expires')),
                ('is_permanent', models.BooleanField(default=False, help_text='Permanent mute (requires admin to remove)')),
                ('mute_posts', models.BooleanField(default=True, help_text='Prevent creating new posts')),
                ('mute_topics', models.BooleanField(default=True, help_text='Prevent creating new topics')),
                ('mute_likes', models.BooleanField(default=False, help_text='Prevent liking posts')),
                ('is_active', models.BooleanField(default=True)),
                ('revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('muted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_mutes', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_mutes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_mutes', to=settings.AUTH_USER_MODEL)),
                ('related_warning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutes', to='Forum.userwarning')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_type', models.CharField(choices=[('general', 'General Note'), ('warning', 'Warning Related'), ('behavior', 'Behavior Pattern'), ('positive', 'Positive Note'), ('context', 'Context/Background'), ('watch', 'Under Watch')], default='general', max_length=20)),
                ('content', models.TextField(help_text='Private note content (only visible to staff)', max_length=5000, validators=[django.core.validators.MinLengthValidator(5)])),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin to top of notes')),
                ('is_important', models.BooleanField(default=False, help_text='Mark as important')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_staff_notes_created', to=settings.AUTH_USER_MODEL)),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_notes', to='Forum.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_staff_notes', to=settings.AUTH_USER_MODEL)),
                ('related_warning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_notes', to='Forum.userwarning')),
            ],
            options={
                'ordering': ['-is_pinned', '-is_important', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('moderator_username', models.CharField(max_length=150)),
                ('action_type', models.CharField(choices=[('warning_issued', 'Warning Issued'), ('warning_acknowledged', 'Warning Acknowledged'), ('mute_applied', 'Mute Applied'), ('mute_revoked', 'Mute Revoked'), ('post_hidden', 'Post Hidden'), ('post_unhidden', 'Post Unhidden'), ('post_deleted', 'Post Deleted'), ('topic_locked', 'Topic Locked'), ('topic_unlocked', 'Topic Unlocked'), ('topic_pinned', 'Topic Pinned'), ('topic_unpinned', 'Topic Unpinned'), ('topic_deleted', 'Topic Deleted'), ('report_assigned', 'Report Assigned'), ('report_resolved', 'Report Resolved'), ('report_escalated', 'Report Escalated'), ('content_recovered', 'Content Recovered'), ('staff_note_added', 'Staff Note Added'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('target_user_username', models.CharField(blank=True, max_length=150)),
                ('target_post_id', models.UUIDField(blank=True, null=True)),
                ('target_topic_id', models.UUIDField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions_received', to=settings.AUTH_USER_MODEL)),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Forum.report')),
                ('related_mute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Forum.usermute')),
                ('related_warning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Forum.userwarning')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostEditHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edited_by_username', models.CharField(max_length=150)),
                ('content_before', models.TextField(help_text='Content before this edit')),
                ('content_after', models.TextField(help_text='Content after this edit')),
                ('edit_reason', models.CharField(blank=True, max_length=200)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('is_minor_edit', models.BooleanField(default=False)),
                ('characters_added', models.IntegerField(default=0)),
                ('characters_removed', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_edits_made', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='Forum.post')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post', '-created_at'], name='Forum_poste_post_id_ecd7f5_idx'), models.Index(fields=['edited_by', '-created_at'], name='Forum_poste_edited__12ad6b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', '-created_at'], name='Forum_repor_status_ca4497_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['assigned_to', 'status'], name='Forum_repor_assigne_ac863e_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reporter', '-created_at'], name='Forum_repor_reporte_f67000_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reported_user', '-created_at'], name='Forum_repor_reporte_7e261d_idx'),
        ),
        migrations.AddIndex(
            model_name='deletedcontent',
            index=models.Index(fields=['content_type', '-created_at'], name='Forum_delet_content_645ab7_idx'),
        ),
        migrations.AddIndex(
            model_name='deletedcontent',
            index=models.Index(fields=['original_author', '-created_at'], name='Forum_delet_origina_aed90e_idx'),
        ),
        migrations.AddIndex(
            model_name='deletedcontent',
            index=models.Index(fields=['deleted_by', '-created_at'], name='Forum_delet_deleted_45aa86_idx'),
        ),
        migrations.AddIndex(
            model_name='userwarning',
            index=models.Index(fields=['user', '-created_at'], name='Forum_userw_user_id_5bc99e_idx'),
        ),
        migrations.AddIndex(
            model_name='userwarning',
            index=models.Index(fields=['issued_by', '-created_at'], name='Forum_userw_issued__b5ff7b_idx'),
        ),
        migrations.AddIndex(
            model_name='usermute',
            index=models.Index(fields=['user', '-created_at'], name='Forum_userm_user_id_f59398_idx'),
        ),
        migrations.AddIndex(
            model_name='usermute',
            index=models.Index(fields=['user', 'is_active', 'ends_at'], name='Forum_userm_user_id_e6fa2f_idx'),
        ),
        migrations.AddIndex(
            model_name='staffnote',
            index=models.Index(fields=['user', '-created_at'], name='Forum_staff_user_id_eefb07_idx'),
        ),
        migrations.AddIndex(
            model_name='staffnote',
            index=models.Index(fields=['created_by', '-created_at'], name='Forum_staff_created_758695_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationlog',
            index=models.Index(fields=['moderator', '-created_at'], name='Forum_moder_moderat_bcbe63_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationlog',
            index=models.Index(fields=['action_type', '-created_at'], name='Forum_moder_action__db7c15_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationlog',
            index=models.Index(fields=['target_user', '-created_at'], name='Forum_moder_target__a5a0f8_idx'),
        ),
    ]
