# Generated by Django 6.0.1 on 2026-01-17 08:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0002_moderationtemplate_report_deletedcontent_userwarning_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Private categories are only visible to allowed users'),
        ),
        migrations.AddField(
            model_name='category',
            name='staff_only',
            field=models.BooleanField(default=False, help_text='Only staff members can access this category'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Announcement title', max_length=200, validators=[django.core.validators.MinLengthValidator(5)])),
                ('message', models.TextField(help_text='Announcement message (supports markdown)', max_length=2000, validators=[django.core.validators.MinLengthValidator(10)])),
                ('announcement_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error/Alert')], default='info', help_text='Visual style of the announcement', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Show this announcement')),
                ('is_dismissible', models.BooleanField(default=True, help_text='Users can dismiss this announcement')),
                ('audience', models.CharField(choices=[('all', 'All Users'), ('authenticated', 'Logged-in Users Only'), ('staff', 'Staff Only')], default='all', help_text='Who should see this announcement', max_length=20)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When to start showing this announcement')),
                ('ends_at', models.DateTimeField(blank=True, help_text='When to stop showing this announcement (leave blank for no expiry)', null=True)),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='Display priority (1=low, 5=high)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times viewed')),
                ('dismiss_count', models.PositiveIntegerField(default=0, help_text='Number of times dismissed')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_created', to=settings.AUTH_USER_MODEL)),
                ('target_category', models.ForeignKey(blank=True, help_text='Show only in specific category (leave blank for global)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='Forum.category')),
            ],
            options={
                'ordering': ['-priority', '-starts_at'],
                'indexes': [models.Index(fields=['is_active', '-priority', '-starts_at'], name='Forum_annou_is_acti_f9ab32_idx'), models.Index(fields=['target_category', 'is_active'], name='Forum_annou_target__49b085_idx')],
            },
        ),
    ]
