# Generated by Django 6.0.4 on 2026-04-19 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0005_fix_missing_announcement_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModerationTemplate',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
