# Generated by Django 6.0.3 on 2026-03-15 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0002_rename_details_encrypted_to_details_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikeyusage',
            name='api_key',
        ),
        migrations.DeleteModel(
            name='ApiKey',
        ),
        migrations.DeleteModel(
            name='ApiKeyUsage',
        ),
    ]
