# Generated by Django 6.0.4 on 2026-04-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0003_remove_apikeyusage_api_key_delete_apikey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csslisting',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('pending', 'Pending'), ('published', 'Published'), ('rejected', 'Rejected')], default='published', max_length=20),
        ),
    ]
