# Generated by Django 6.0.4 on 2026-04-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0004_alter_csslisting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csslisting',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('pending', 'Pending'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='published', max_length=20),
        ),
    ]
