# Generated by Django 6.0.4 on 2026-04-15 12:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0005_add_archived_to_csslisting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerplan',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.70'), help_text='Fraction of sale revenue paid to developer (e.g. 0.70 = 70%).', max_digits=4),
        ),
    ]
