# Generated by Django 6.0.4 on 2026-04-19 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Moderation', '0002_fix_missing_tables'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnnouncementDismissal',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='ModerationTemplate',
        ),
    ]
