# Generated by Django 6.0.1 on 2026-01-10 10:26

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CssCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CSS Category',
                'verbose_name_plural': 'CSS Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Download Log',
                'verbose_name_plural': 'Download Logs',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='css',
            options={'ordering': ['-created_at'], 'verbose_name': 'CSS File', 'verbose_name_plural': 'CSS Files'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchased_at'], 'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
        migrations.AlterField(
            model_name='css',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='css',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price_paid',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['user', '-purchased_at'], name='Api_purchas_user_id_b01a60_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['css_file', '-purchased_at'], name='Api_purchas_css_fil_8ffb39_idx'),
        ),
        migrations.AddField(
            model_name='css',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='css_files', to='Api.csscategory'),
        ),
        migrations.AddIndex(
            model_name='css',
            index=models.Index(fields=['creator', '-created_at'], name='Api_css_creator_244f05_idx'),
        ),
        migrations.AddIndex(
            model_name='css',
            index=models.Index(fields=['category', '-created_at'], name='Api_css_categor_e25295_idx'),
        ),
        migrations.AddIndex(
            model_name='css',
            index=models.Index(fields=['price'], name='Api_css_price_36db77_idx'),
        ),
        migrations.AddField(
            model_name='downloadlog',
            name='css_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='Api.css'),
        ),
        migrations.AddField(
            model_name='downloadlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='css_downloads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='downloadlog',
            index=models.Index(fields=['user', '-downloaded_at'], name='Api_downloa_user_id_fd6097_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadlog',
            index=models.Index(fields=['css_file', '-downloaded_at'], name='Api_downloa_css_fil_cb3cbd_idx'),
        ),
    ]
