# Generated by Django 6.0.1 on 2026-01-10 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_csscategory_downloadlog_alter_css_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlog',
            name='css_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='purchase',
            name='css_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='downloadlog',
            name='css_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_logs', to='Api.css'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='css_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='Api.css'),
        ),
    ]
