# Generated by Django 4.2.6 on 2026-04-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_css_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='css',
            name='html_template',
            field=models.TextField(blank=True, default='<div class="loader"></div>', help_text='Custom HTML structure for rendering the preview'),
        ),
    ]
