# Generated by Django 5.2.1 on 2025-06-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=200, unique=True)),
                ('skey', models.CharField(max_length=200)),
                ('_from', models.CharField(max_length=16)),
                ('to', models.CharField(max_length=16)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
