# Generated by Django 6.0.4 on 2026-04-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0004_beneficiary_bankcard_limits_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcard',
            name='payment_number',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
    ]
