# Generated by Django 6.0.4 on 2026-04-27 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0005_alter_bankcard_payment_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankcard',
            name='daily_limit',
        ),
        migrations.RemoveField(
            model_name='bankcard',
            name='monthly_limit',
        ),
        migrations.RemoveField(
            model_name='bankcard',
            name='transaction_alerts_enabled',
        ),
        migrations.RemoveField(
            model_name='bankcard',
            name='weekly_limit',
        ),
    ]
