# Generated by Django 6.0.2 on 2026-02-23 17:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Plain text or markdown. Will be auto-escaped in templates.', max_length=2000)),
                ('image_url', models.URLField(blank=True, help_text='Optional image URL for the ad banner.', max_length=500)),
                ('target_url', models.URLField(help_text='URL to redirect users to when they click the ad.', max_length=500)),
                ('budget_neuros', models.DecimalField(decimal_places=2, default=0, help_text='Total budget allocated for this ad in Neuros.', max_digits=10)),
                ('spent_neuros', models.DecimalField(decimal_places=2, default=0, help_text='Amount spent so far in Neuros.', max_digits=10)),
                ('placement_zone', models.CharField(choices=[('shop_sidebar', 'Shop Sidebar'), ('forum_banner', 'Forum Banner'), ('homepage_banner', 'Homepage Banner')], db_index=True, default='shop_sidebar', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, help_text='Leave blank for no expiry.', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (staff only).', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_impressions', to=settings.AUTH_USER_MODEL)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='Advertisement.advertisement')),
            ],
            options={
                'verbose_name': 'Ad Impression',
                'verbose_name_plural': 'Ad Impressions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_clicks', to=settings.AUTH_USER_MODEL)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='Advertisement.advertisement')),
            ],
            options={
                'verbose_name': 'Ad Click',
                'verbose_name_plural': 'Ad Clicks',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['advertiser', '-created_at'], name='Advertiseme_adverti_bc521b_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['placement_zone', 'status'], name='Advertiseme_placeme_6ec678_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='Advertiseme_status_45bcb0_idx'),
        ),
        migrations.AddIndex(
            model_name='adimpression',
            index=models.Index(fields=['advertisement', '-timestamp'], name='Advertiseme_adverti_af17ee_idx'),
        ),
        migrations.AddIndex(
            model_name='adclick',
            index=models.Index(fields=['advertisement', '-timestamp'], name='Advertiseme_adverti_20c83a_idx'),
        ),
    ]
