# Generated by Django 6.0.2 on 2026-02-24 19:52

import Advertisement.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adimpression',
            name='zone',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='body_html',
            field=models.TextField(blank=True, editable=False, help_text='Auto-generated sanitized HTML from body markdown. Do not edit directly.'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='cost_neuros',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Computed campaign cost in Neuros (rate_per_day × days). Set on activation.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='payment_tx_ref',
            field=models.CharField(blank=True, help_text='VRC Banking transaction reference for the ad payment.', max_length=100),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='body',
            field=models.TextField(help_text='Supports markdown formatting (bold, italic, lists, links). Max 2000 characters.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Required for billing. Leave blank for no expiry (billing will not apply).', null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional primary image URL for the ad banner.', max_length=500),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='placement_zone',
            field=models.CharField(choices=[('shop_sidebar', 'Shop Sidebar'), ('forum_banner', 'Forum Banner'), ('homepage_banner', 'Homepage Banner'), ('all', 'All Zones')], db_index=True, default='shop_sidebar', max_length=30),
        ),
        migrations.CreateModel(
            name='AdvertisementImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='JPG, PNG or GIF. Max 5 MB.', upload_to=Advertisement.models.advertisement_image_upload_path)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (lower numbers appear first).')),
                ('alt_text', models.CharField(blank=True, help_text='Accessible alt text for this image.', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Advertisement.advertisement')),
            ],
            options={
                'verbose_name': 'Advertisement Image',
                'verbose_name_plural': 'Advertisement Images',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
