# Generated by Django 6.0.4 on 2026-04-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisement', '0003_alter_advertisement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20),
        ),
    ]
