# Generated by Django 6.0.2 on 2026-02-07 20:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotResponseFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flagged_by_session', models.CharField(blank=True, help_text='Session ID for anonymous flaggers', max_length=255, null=True)),
                ('reason', models.CharField(choices=[('inaccurate', 'Inaccurate Information'), ('inappropriate', 'Inappropriate Content'), ('unhelpful', 'Unhelpful Response'), ('offensive', 'Offensive Language'), ('misleading', 'Misleading Information'), ('security_concern', 'Security Concern'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional details about the issue', max_length=2000, validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=15)),
                ('resolution_notes', models.TextField(blank=True, help_text='Staff notes on how the flag was resolved', max_length=2000)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_flags_assigned', to=settings.AUTH_USER_MODEL)),
                ('chat_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='Chatbot.chatmessage')),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_flags_filed', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_flags_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotResponseEdit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_response', models.TextField(help_text='Original chatbot response before edit')),
                ('edited_response', models.TextField(help_text='Edited response content')),
                ('edit_reason', models.CharField(help_text='Reason for editing the response', max_length=500, validators=[django.core.validators.MinLengthValidator(5)])),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('review_notes', models.TextField(blank=True, max_length=1000)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='Chatbot.chatmessage')),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_edits_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_edits_reviewed', to=settings.AUTH_USER_MODEL)),
                ('related_flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edits', to='Chatbot.chatbotresponseflag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotModerationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_username', models.CharField(max_length=150)),
                ('action_type', models.CharField(choices=[('flag_created', 'Response Flagged'), ('flag_assigned', 'Flag Assigned'), ('flag_resolved', 'Flag Resolved'), ('flag_dismissed', 'Flag Dismissed'), ('response_edited', 'Response Edited'), ('edit_approved', 'Edit Approved'), ('edit_rejected', 'Edit Rejected'), ('kb_entry_created', 'Knowledge Entry Created'), ('kb_entry_updated', 'Knowledge Entry Updated'), ('kb_entry_deleted', 'Knowledge Entry Deleted'), ('kb_entry_toggled', 'Knowledge Entry Toggled'), ('quality_scored', 'Quality Score Assigned'), ('bulk_action', 'Bulk Action Performed'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional action metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_mod_actions', to=settings.AUTH_USER_MODEL)),
                ('target_knowledge_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to='Chatbot.knowledgebase')),
                ('target_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to='Chatbot.chatmessage')),
                ('target_flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to='Chatbot.chatbotresponseflag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotKnowledgeModeration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Entry Created'), ('updated', 'Entry Updated'), ('activated', 'Entry Activated'), ('deactivated', 'Entry Deactivated'), ('deleted', 'Entry Deleted'), ('reviewed', 'Entry Reviewed')], max_length=15)),
                ('reason', models.TextField(blank=True, help_text='Reason for the moderation action', max_length=1000)),
                ('previous_question', models.TextField(blank=True)),
                ('previous_answer', models.TextField(blank=True)),
                ('new_question', models.TextField(blank=True)),
                ('new_answer', models.TextField(blank=True)),
                ('previous_category', models.CharField(blank=True, max_length=100)),
                ('new_category', models.CharField(blank=True, max_length=100)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('knowledge_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_history', to='Chatbot.knowledgebase')),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_kb_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Knowledge Base Moderation Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['knowledge_entry', '-created_at'], name='Chatbot_cha_knowled_eda309_idx'), models.Index(fields=['action', '-created_at'], name='Chatbot_cha_action_1ac5ba_idx'), models.Index(fields=['moderator', '-created_at'], name='Chatbot_cha_moderat_b6e422_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatbotQualityScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accuracy_score', models.PositiveSmallIntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Acceptable'), (4, 'Good'), (5, 'Excellent')], help_text='How accurate is the response?')),
                ('helpfulness_score', models.PositiveSmallIntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Acceptable'), (4, 'Good'), (5, 'Excellent')], help_text='How helpful is the response?')),
                ('tone_score', models.PositiveSmallIntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Acceptable'), (4, 'Good'), (5, 'Excellent')], help_text='How appropriate is the tone?')),
                ('overall_score', models.PositiveSmallIntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Acceptable'), (4, 'Good'), (5, 'Excellent')], help_text='Overall quality rating')),
                ('notes', models.TextField(blank=True, help_text='Additional quality notes', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_scores', to='Chatbot.chatmessage')),
                ('scored_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_quality_scores_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['chat_message', '-created_at'], name='Chatbot_cha_chat_me_4e906b_idx'), models.Index(fields=['scored_by', '-created_at'], name='Chatbot_cha_scored__3e111a_idx')],
                'unique_together': {('chat_message', 'scored_by')},
            },
        ),
        migrations.AddIndex(
            model_name='chatbotresponseflag',
            index=models.Index(fields=['status', '-created_at'], name='Chatbot_cha_status_b40996_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotresponseflag',
            index=models.Index(fields=['severity', 'status'], name='Chatbot_cha_severit_feb058_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotresponseflag',
            index=models.Index(fields=['assigned_to', 'status'], name='Chatbot_cha_assigne_1f38f7_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotresponseedit',
            index=models.Index(fields=['chat_message', '-created_at'], name='Chatbot_cha_chat_me_505096_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotresponseedit',
            index=models.Index(fields=['approval_status', '-created_at'], name='Chatbot_cha_approva_6fe224_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotresponseedit',
            index=models.Index(fields=['edited_by', '-created_at'], name='Chatbot_cha_edited__6dd212_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotmoderationaction',
            index=models.Index(fields=['actor', '-created_at'], name='Chatbot_cha_actor_i_4491b9_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotmoderationaction',
            index=models.Index(fields=['action_type', '-created_at'], name='Chatbot_cha_action__6ca1e9_idx'),
        ),
    ]
