# Generated by Django 6.0.3 on 2026-03-11 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0003_rename_app_to_todo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mission',
            table=None,
        ),
    ]
